# Hadolint configuration file

# Configure ignore rules
# https://github.com/hadolint/hadolint#rules for a list of available rules.
# Online Linter
# https://hadolint.github.io/hadolint/
ignored:
  - DL3003 # Use WORKDIR to switch to a directory
  - DL3008 # Pin versions in apt get install
  - DL3013 # Pin versions in pip
  - DL3009 # Delete the apt-get lists after installing something
  - DL4001 # Either use Wget or Curl but not both.
  - SC2086 # Double quote to prevent globbing and word splitting.
trustedRegistries:
  - docker.io
  - ghcr.io
