# Online Linter: https://hadolint.github.io/hadolint/
# Rules:         https://github.com/hadolint/hadolint?tab=readme-ov-file#rules
ignored:
  - DL3003 # Use WORKDIR to switch to a directory
  - DL3008 # Pin versions in apt get install
  - DL3009 # Delete the apt-get lists after installing something
  - DL4001 # Either use Wget or Curl but not both.
  - SC2086 # Double quote to prevent globbing and word splitting.
trustedRegistries:
  - docker.io
  - ghcr.io
