# frozen_string_literal: true

source 'https://rubygems.org'

gem 'jekyll', '~> 4.4.1'

group :jekyll_plugins do
  #gem 'jekyll-feed', '~> 0.12'
  #gem 'jekyll-seo-tag', '~> 2.7'
  gem 'jekyll-sitemap', '~> 1.4'
  gem 'jekyll-datapage-generator'
end